name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - run: dotnet publish --configuration Release -r win-x64 --self-contained true

      - name: Install ILLink
        run: dotnet tool install -g il-linker

      - name: Link assemblies
        run: il-linker -c Release -p UEVR.csproj -o linked-output

      - name: Compress release
        run: |
          7z a ${{github.workspace}}/ActionsRelease.zip linked-output

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: UEVR
          path: ${{github.workspace}}/ActionsRelease.zip
          if-no-files-found: error
