name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - run: dotnet build --configuration Release

      - name: Compress release
        run: |
          7z a -tzip ${{github.workspace}}/ActionsRelease.zip ${{github.workspace}}/UnrealVR/bin/Release/net6.0-windows/*.*

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: UnrealVR
          path: ${{github.workspace}}/ActionsRelease.zip
          if-no-files-found: error