name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - run: dotnet publish --configuration Release -r win-x64 --self-contained true

      - name: Compress release
        run: |
          7z a ${{github.workspace}}/ActionsRelease.zip ${{github.workspace}}/UEVR/bin/Release/net6.0-windows/win-x64/publish

      - name: Set current time as an environment variable
        id: set_time
        run: echo "TIME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Display current time
        run: echo "Current time: $TIME"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: UEVR-Frontend-${{ TIME }}
          path: ${{github.workspace}}/ActionsRelease.zip
          if-no-files-found: error
